defaults:
  - env/isaaclab_stack_cube@env.train
  - env/isaaclab_stack_cube@env.eval
  - model/gr00t@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
      env: 0
      rollout: 1
      actor: 2

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: user
    experiment_name: "isaaclab_ppo_gr00t_demo"
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 2
  max_steps: -1

  only_eval: False
  val_check_interval: -1
  save_interval: 100

  resume_dir: null # Optional: path to a saved checkpoint directory, such as 'checkpoints/global_step_10'. If not None, it will be used to resume training.
  ckpt_path: null  # Optional: path to a .pt checkpoint. If not None, it will be loaded after the model is instantiated (for evaluation).

algorithm:
  normalize_advantages: True
  kl_penalty: kl  # how to estimate kl divergence: kl or kl_penalty
  group_size: 1
  reward_coef: 1.0
  rollout_epoch: 1
  eval_rollout_epoch: 1 # set eval_rollout_epoch > 0 when enable runner.only_eval or runner.val_check_interval > 0

  reward_type: chunk_level
  logprob_type: chunk_level
  entropy_type: chunk_level

  update_epoch: 1
  adv_type: gae
  loss_type: actor_critic
  loss_agg_func: "token-mean" 
  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.2
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0

  gamma: 0.99
  gae_lambda: 0.95

  filter_rewards: False
  rewards_lower_bound: 0.1
  rewards_upper_bound: 0.9
  # params for generation
  sampling_params:
    do_sample: True
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 50
    top_p: 1.0
    repetition_penalty: 1.0
    add_BOS: False

  # length argument for autoregressive sampling
  # max length means max amount of tokens to generate
  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  enable_offload: False

  # Override the default values in env/isaaclab_stack_cube
  train:
    total_num_envs: 1
    max_episode_steps: 288
    max_steps_per_rollout_epoch: 288
    use_fixed_reset_state_ids: True

  eval:
    total_num_envs: 1
    max_episode_steps: 288
    max_steps_per_rollout_epoch: 288
    auto_reset: True
    ignore_terminations: True
    use_fixed_reset_state_ids: True
    video_cfg:
      save_video: True
      info_on_video: True
      video_base_dir: ${runner.logger.log_path}/video/eval

rollout:
  group_name: "RolloutGroup"
  backend: "huggingface"
  enable_offload: True
  pipeline_stage_num: 1

  model:
    model_path: "/path/to/isaaclab_stack_cube_gr00t_ckpt"
    precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 1
  global_batch_size: 2
  seed: 1234
  enable_offload: False

  # Override the default values in model/gr00t
  model:
    model_path: "/path/to/isaaclab_stack_cube_gr00t_ckpt"
    add_value_head: True
    embodiment_tag: "isaaclab_franka"
    obs_converter_type: "isaaclab_stack_cube"
    num_action_chunks: 16

  optim:
    lr: 2.0e-5
    value_lr: 2.0e-5
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    clip_grad: 1.0
    weight_decay: 0.01
    critic_warmup_steps: 0
  
  # Override the default values in training_backend/fsdp
  fsdp_config:
    strategy: "fsdp"
    gradient_checkpointing: True
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False
