defaults:
  - env/libero_spatial@env.train
  - env/libero_spatial@env.eval
  - model/pi0@actor.model 
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor: 0-1
    rollout, env: 2-3
runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "async_dagger_sft_openpi_libero_spatial"
    logger_backends: ["tensorboard"]

  max_epochs: 8000
  max_steps: -1
  
  only_eval: False
  val_check_interval: 15
  save_interval: 4500000000

algorithm:
  expert_intervention_rate: 0.99
  expert_intervention_rate_schedule: "exponential"
  expert_intervention_rate_min: 0.05
  expert_intervention_rate_decay_steps: 100
  expert_intervention_rate_decay_factor: 0.99  # Decay factor for exponential schedule (only used if schedule="exponential")
  only_save_intervened: False
  sampling_ratio: 0.0

  rollout_epoch: 5000
  eval_rollout_epoch: 2
  
  update_epoch: 1
  group_size: 1
  
  replay_buffer_capacity: 30000
  min_buffer_size: 1024
  
  adv_type: gae
  loss_type: embodied_sac
  loss_agg_func: "token-mean"
  
  bootstrap_type: always
  gamma: 0.8
  tau: 0.01
  auto_entropy_tuning: True
  alpha_type: softplus
  initial_alpha: 0.01
  target_entropy: -4
  alpha_lr: 3.0e-4
  target_update_freq: 1
  agg_q: min
  
  sampling_params:
    do_sample: True
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 50
    top_p: 1.0
    repetition_penalty: 1.0

  length_params:
    max_new_token: 7
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  enable_offload: False

  train:
    total_num_envs: 32
    auto_reset: True
    ignore_terminations: True
    use_fixed_reset_state_ids: False
    max_episode_steps: 240
    max_steps_per_rollout_epoch: 240
  
  eval:
    total_num_envs: 32
    auto_reset: True
    ignore_terminations: True
    max_episode_steps: 240
    max_steps_per_rollout_epoch: 240
    use_fixed_reset_state_ids: True
    group_size: 1
    video_cfg:
      save_video: True
      video_base_dir: ${runner.logger.log_path}/video/eval

rollout:
  group_name: "RolloutGroup"
  backend: "huggingface"
  model_dir: ""
  enable_offload: False
  pipeline_stage_num: 1

  model:
    model_path: "/home/ysa/dagger/ckpt/libero-sft"
    precision: ${actor.model.precision}

  expert_model:
    model_path: "/home/ysa/dagger/ckpt/libero-final"
    precision: ${actor.expert_model.precision}

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"

  micro_batch_size: 32
  global_batch_size: 128
  seed: 1234
  enable_offload: False

  model:
    model_name: "openpi"
    model_path: "/home/ysa/dagger/ckpt/libero-sft"
    action_dim: 7
    
    precision: null
    add_value_head: True

    openpi:
      config_name: "pi0_libero"
      detach_critic_input: True
      train_expert_only: True
  
  compile_model: True

  expert_model:
    model_name: "openpi"
    model_path: "/home/ysa/dagger/ckpt/libero-final"
    action_dim: 7
    
    precision: null
    add_value_head: True
    openpi:
      config_name: "pi0_libero"
      detach_critic_input: True
      train_expert_only: True

  optim:
    lr: 1e-5
    value_lr: 1.55e-4
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    weight_decay: 1.0e-10
    clip_grad: 5.0
    warmup_style: "cosine"  
    lr_warmup_steps: 20
    total_training_steps: 4000  # for lr scheduler cosine decay

  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "no_shard"
    use_orig_params: True
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False

initial_sft_data_path: ""