defaults:
  - env/libero_spatial@env.train
  - env/libero_spatial@env.eval
  - model/openvla_oft@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor,env,rollout: all

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: user
    experiment_name: "libero_spatial_grpo_openvlaoft"
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 1000
  max_steps: -1

  only_eval: False
  val_check_interval: -1
  save_interval: 25

  resume_dir: null # Optional: path to a saved checkpoint directory, such as 'checkpoints/global_step_10'. If not None, it will be used to resume training.
  ckpt_path: null  # Optional: path to a .pt checkpoint. If not None, it will be loaded after the model is instantiated (for evaluation).

algorithm:
  normalize_advantages: True
  kl_penalty: kl  # how to estimate kl divergence: kl or kl_penalty
  group_size: 8
  rollout_epoch: 16
  eval_rollout_epoch: 1 # set eval_rollout_epoch > 0 when enable runner.only_eval or runner.val_check_interval > 0

  reward_type: action_level  # action_level or chunk_level
  logprob_type: token_level
  entropy_type: token_level

  adv_type: grpo
  loss_type: actor
  loss_agg_func: "token-mean"
  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.28
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0

  gamma: 0.99
  gae_lambda: 0.95

  reward_coef: 5.0

  sampling_params:
    do_sample: True
    temperature_train: 1.6
    temperature_eval: 1.6
    top_k: -1
    top_p: 1.0
    repetition_penalty: 1.0

  # length argument for autoregressive sampling
  # max length means max amount of tokens to generate
  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

  filter_rewards: True
  rewards_lower_bound: 0.5
  rewards_upper_bound: 4.5

env:
  group_name: "EnvGroup"
  enable_offload: False

  # Override the default values in env/libero_spatial
  train:
    total_num_envs: 64
    group_size: ${algorithm.group_size}
    max_episode_steps: 512 # max episode steps for truncation
    max_steps_per_rollout_epoch: 512
    reward_coef: ${algorithm.reward_coef}
    reset_gripper_open: False
  eval:
    total_num_envs: 500
    auto_reset: True
    ignore_terminations: True
    max_episode_steps: 512
    max_steps_per_rollout_epoch: 512
    group_size: 1
    reset_gripper_open: False
    is_eval: True
    video_cfg:
      save_video: True
      video_base_dir: ${runner.logger.log_path}/video/eval

rollout:
  group_name: "RolloutGroup"
  generation_backend: "huggingface"
  enable_offload: True
  pipeline_stage_num: 1

  model:
    model_path: "/path/to/model/Openvla-oft-SFT-libero-spatial-traj1/"
    precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 32
  global_batch_size: 16384
  seed: 1234
  enable_offload: True

  # Override the default values in model/openvla_oft
  model:
    model_path: "/path/to/model/Openvla-oft-SFT-libero-spatial-traj1/"
    model_type: "openvla_oft"

    unnorm_key: libero_spatial_no_noops
    max_prompt_length: 128

  optim:
    lr: 2.0e-5
    value_lr: 3.0e-3
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-08
    weight_decay: 0.01
    clip_grad: 1.0

  # Override the default values in training_backend/fsdp
  fsdp_config:
    strategy: "fsdp"
    gradient_checkpointing: True
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False