defaults:
  - env/maniskill_put_on_plate_in_scene_25_main@env.train
  - env/maniskill_put_on_plate_in_scene_25_main@env.eval
  - model/pi0@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor,env,rollout: all

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: user
    experiment_name: "maniskill_ppo_openpi"
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 1000
  max_steps: -1
  only_eval: False
  val_check_interval: 10
  save_interval: 50

  resume_dir: null # Optional: path to a saved checkpoint directory, such as 'checkpoints/global_step_10'. If not None, it will be used to resume training.
  ckpt_path: null  # Optional: path to a .pt checkpoint. If not None, it will be loaded after the model is instantiated (for evaluation).

algorithm:
  normalize_advantages: True
  kl_penalty: kl  # how to estimate kl divergence: kl or kl_penalty
  group_size: 1
  reward_coef: 1.0

  rollout_epoch: 1
  eval_rollout_epoch: 1 # set eval_rollout_epoch > 0 when enable runner.only_eval or runner.val_check_interval > 0
  reward_type: chunk_level
  logprob_type: token_level
  entropy_type: chunk_level
  update_epoch: 4
  
  adv_type: gae
  loss_type: actor_critic
  loss_agg_func: "token-mean" 
  kl_beta: 0.0
  entropy_bonus: 0.005
  clip_ratio_high: 0.2
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0

  gamma: 0.99
  gae_lambda: 0.95

  filter_rewards: False
  rewards_lower_bound: 0.0
  rewards_upper_bound: 1.0
  # params for generation
  sampling_params:
    do_sample: True
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 50
    top_p: 1.0
    repetition_penalty: 1.0
    add_BOS: False

  # length argument for autoregressive sampling
  # max length means max amount of tokens to generate
  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  enable_offload: False
  # Override the default values in env/train or env/eval
  train:
    total_num_envs: 320
    auto_reset: True
    use_fixed_reset_state_ids: False
    max_episode_steps: 80 # max episode steps for truncation
    max_steps_per_rollout_epoch: 80
    init_params:
      use_multiple_plates: False
  eval:
    total_num_envs: 320
    auto_reset: True
    ignore_terminations: True
    max_episode_steps: 80
    max_steps_per_rollout_epoch: 80
    use_fixed_reset_state_ids: True
    group_size: ${algorithm.group_size}
    is_eval: True
    video_cfg:
      save_video: True
      video_base_dir: ${runner.logger.log_path}/video/eval
    init_params:
      use_multiple_plates: False

rollout:
  group_name: "RolloutGroup"
  generation_backend: "huggingface"
  recompute_logprobs: False
  unnorm_key: libero_10
  enable_offload: False
  pipeline_stage_num: 1

  model:
    model_path: "/path/to/model/USER-Pi0-ManiSkill-25Main-SFT"
    precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 32      # how many samples each GPU processes per sampling step
  global_batch_size: 5120   # after how many sampled examples we perform one loss backward pass. Requirement: global bz must be '_world_size' multiples of local bs.
  seed: 0
  enable_offload: False
  # Override the default values in model/pi0
  model:
    model_path: "/path/to/model/USER-Pi0-ManiSkill-25Main-SFT"
    model_name: "openpi"
    precision: null    # bf16
    num_action_chunks: 5 # interface for the env
    action_dim: 7
    add_value_head: True
    # openpi specific parameters
    openpi:
      config_name: "pi0_maniskill"
      num_images_in_input: 1
      noise_method: "flow_noise"
      action_horizon: 8
      noise_params: [0.16, 0.12, 200]
      detach_critic_input: True
      joint_logprob: True # False for flow_sde, True for flow_noise     
      value_after_vlm: False      # pi0: False. pi0.5: True
    policy_setup: widowx_bridge

  optim:
    lr: 7.91e-6
    value_lr: 1.55e-4
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    clip_grad: 1.0
    critic_warmup_steps: 0

  # Override the default values in training_backend/fsdp
  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "no_shard"
    gradient_checkpointing: False # for openpi, gradient checkpointing is not supported, please do not change this value
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}
reward:
  use_reward_model: False

critic:
  use_critic_model: False