defaults:
  - env/robotwin_place_empty_cup@env.train
  - env/robotwin_place_empty_cup@env.eval
  - model/openvla_oft@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null 
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/
    
cluster:
  num_nodes: 1
  component_placement:
    env: 0-7
    rollout: 0-7
    actor: 0-7

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: user
    experiment_name: "test_openvla"
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 1000
  max_steps: -1

  only_eval: True
  val_check_interval: -1
  save_interval: 100
  
  resume_dir: null # Optional: path to a saved checkpoint directory, such as 'checkpoints/global_step_10'. If not None, it will be used to resume training.
  ckpt_path: null  # Optional: path to a .pt checkpoint. If not None, it will be loaded after the model is instantiated (for evaluation).

algorithm:
  normalize_advantages: True
  kl_penalty: kl  # how to estimate kl divergence: kl or kl_penalty
  group_size: 1

  rollout_epoch: 1 # 16
  eval_rollout_epoch: 1
  reward_type: chunk_level
  logprob_type: token_level
  entropy_type: token_level

  adv_type: gae
  loss_type: actor_critic
  loss_agg_func: "token-mean"
  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.28
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0


  gamma: 0.99
  gae_lambda: 0.95

  # params for rollout
  sampling_params:
    do_sample: False
    temperature_train: 1.6
    temperature_eval: -1 # -1 means do_sample=False during evaluation
    top_k: -1
    top_p: 1.0
    repetition_penalty: 1.0

  # length argument for autoregressive sampling
  # max length means max amount of tokens to generate
  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  enable_offload: False
  eval:
    total_num_envs: 256
    auto_reset: True
    ignore_terminations: True
    max_episode_steps: 200
    max_steps_per_rollout_epoch: 200
    group_size: 1
    use_fixed_reset_state_ids: True
    is_eval: True
    assets_path: "/path/to/robotwin_assets"
    seeds_path: ${oc.env:REPO_PATH}/user/envs/robotwin/seeds/eval_seeds.json
    video_cfg:
      save_video: True
      video_base_dir: ${runner.logger.log_path}/video/eval

rollout:
  group_name: "RolloutGroup"
  backend: "huggingface"
  enable_offload: False
  pipeline_stage_num: 1
  model:
    model_type: "openvla_oft"
    model_path: ${actor.model.model_path}
    precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 1 # 1
  global_batch_size: 40 # 640
  seed: 1234
  enable_offload: True

  model:
    model_path: "/path/to/USER/USER-OpenVLAOFT-RoboTwin-SFT-place_empty_cup"
    model_type: "openvla_oft"
    implement_version: "offical"
    value_type: ${algorithm.reward_type}  # 'action' or 'token'
    action_dim: 14
    use_proprio: True
    proprio_dim: 14
    use_film: False

    num_action_chunks: 25
    unnorm_key: place_empty_cup_1k
    center_crop: True

    add_value_head: True

    max_prompt_length: 512

  optim:
    lr: 1.0e-4
    value_lr: 3.0e-3
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-05
    clip_grad: 10.0

  # Override the default values in training_backend/fsdp
  fsdp_config:
    strategy: "fsdp"
    gradient_checkpointing: False
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False