env_type: libero
task_suite_name: libero_130

total_num_envs: null

auto_reset: False
ignore_terminations: False
max_steps_per_rollout_epoch: 512
max_episode_steps: 512 # max episode steps for truncation

use_rel_reward: True
reward_coef: 1.0

# USER LiberoEnv specific settings
reset_gripper_open: True
is_eval: False

seed: 0
group_size: 1
use_fixed_reset_state_ids: True
use_ordered_reset_state_ids: True

video_cfg:
  save_video: True
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/train

init_params:
  camera_heights: 256
  camera_widths: 256
